### ISSUE TITLE
Impossible to run app since 0.0.4 version

### ISSUE THREAD

**Issue by matichouraider** [iampawan/Flute-Music-Player#1]
Hello,

I have installed the version 0.0.3 of this plugin and it work fine. But since the release of 0.0.4 version, the 0.0.3 version is unavailable and the 0.0.4 don't work. When I try to run the app I get this error : 

> Execution failed for task ':flute_music_player:compileDebugJavaWithJavac'

It's now impossible to launch the app.

You can see it on this screenshot.

<img width="1332" alt="capture d ecran 2018-04-02 a 00 29 02" src="https://user-images.githubusercontent.com/30347804/38178190-b6a89952-360d-11e8-96a5-2f416a7f50b7.png">

thanks a lot.

**Comment by iampawan** [comment]
Before merging this .. can you tell me which version of flutter is causing this issue ?

**Comment by iampawan** [comment]
Closed in #2
